In [1]:
import torch

In [9]:
torch.tensor([1, 2, 3], dtype=torch.float16, requires_grad=True)

tensor([1., 2., 3.], dtype=torch.float16, requires_grad=True)

In [17]:
x = torch.randn(4, 4)
x.view(-1).numpy()

array([ 0.2576796 ,  0.55031323, -1.98067   ,  0.14588705,  1.2137071 ,
       -0.968189  , -0.9299276 ,  0.82199186, -0.7504303 ,  1.4889988 ,
        1.193639  , -0.23396792, -1.4901247 ,  2.0771086 ,  0.26926687,
        0.6901397 ], dtype=float32)

In [21]:
print(torch.cuda.is_available())
device = torch.device("cuda")
x = torch.rand(2, 2).to(device)
x

True


tensor([[0.2219, 0.4063],
        [0.5314, 0.6071]], device='cuda:0')

In [24]:
x = torch.randn(3, requires_grad=True)
y = x + 2
print(x)
print(y)
print(y.grad_fn)

tensor([-0.1104, -0.7776,  1.0558], requires_grad=True)
tensor([1.8896, 1.2224, 3.0558], grad_fn=<AddBackward0>)


In [31]:
z = y * y * 3
print(z)
z = z.mean()
print(z)

print(x.grad)
z.backward()
print(x.grad)

tensor([10.7117,  4.4826, 28.0144], grad_fn=<MulBackward0>)
tensor(14.4029, grad_fn=<MeanBackward0>)
tensor([3.7792, 2.4448, 6.1117])
tensor([ 7.5584,  4.8895, 12.2233])


In [44]:
nums = list(range(1, 11))
X = torch.tensor(nums, dtype=torch.float32)
Y = torch.tensor([2*x for x in nums], dtype=torch.float32)

w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)

def forward(x):
    return w * x

def loss(y, y_pred):
    return ((y_pred - y)**2).mean()

#forward(X_test).item()

learning_rate = 0.01
n_epoch = 10

for epoch in range(n_epoch):
    y_pred = forward(X)
    l = loss(Y, y_pred)
    l.backward()

    with torch.no_grad():
        w -= learning_rate * w.grad
    w.grad.zero_()

    print(f"epoch {epoch + 1}: w={w.item():.3f}, loss={l.item():.3f}")

for n in nums:
    print(f"f({n}) = {forward(n).item():.3f}")
    


epoch 1: w=1.540, loss=154.000
epoch 2: w=1.894, loss=8.147
epoch 3: w=1.976, loss=0.431
epoch 4: w=1.994, loss=0.023
epoch 5: w=1.999, loss=0.001
epoch 6: w=2.000, loss=0.000
epoch 7: w=2.000, loss=0.000
epoch 8: w=2.000, loss=0.000
epoch 9: w=2.000, loss=0.000
epoch 10: w=2.000, loss=0.000
f(1) = 2.000
f(2) = 4.000
f(3) = 6.000
f(4) = 8.000
f(5) = 10.000
f(6) = 12.000
f(7) = 14.000
f(8) = 16.000
f(9) = 18.000
f(10) = 20.000


In [ ]:
import torch
import torch.nn as nn

nums = [[n] for n in range(1, 11)]
nums2 = [[2*n] for n in range(1, 11)]
X = torch.tensor(nums, dtype=torch.float32)
Y = torch.tensor(nums2, dtype=torch.float32)

n_samples, n_features = X.shape

class LinearRegression(nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self._lin = nn.Linear(input_dim, output_dim)

    def forward(self, x):
        return self._lin(x)

input_size, output_size = n_features, n_features

model = LinearRegression(input_size, output_size)

learning_rate = 0.01
n_epoch = 100

loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(n_epoch):
    y_pred = model(X)
    l = loss(Y, y_pred)
    l.backward()
    optimizer.step()
    optimizer.zero_grad()

    if (epoch+1) % 10 == 0:
        w, b = model.parameters()
        print(f"epoch {epoch+1}: {w=}, {l=}")

for n in nums:
    print(f"f({n}) = {model(n).item():.3f}")


epoch 10: w=Parameter containing:
tensor([[1.9200]], requires_grad=True), l=tensor(0.0671, grad_fn=<MseLossBackward0>)
epoch 20: w=Parameter containing:
tensor([[1.9233]], requires_grad=True), l=tensor(0.0616, grad_fn=<MseLossBackward0>)
epoch 30: w=Parameter containing:
tensor([[1.9264]], requires_grad=True), l=tensor(0.0567, grad_fn=<MseLossBackward0>)
epoch 40: w=Parameter containing:
tensor([[1.9295]], requires_grad=True), l=tensor(0.0521, grad_fn=<MseLossBackward0>)
epoch 50: w=Parameter containing:
tensor([[1.9324]], requires_grad=True), l=tensor(0.0479, grad_fn=<MseLossBackward0>)
epoch 60: w=Parameter containing:
tensor([[1.9352]], requires_grad=True), l=tensor(0.0440, grad_fn=<MseLossBackward0>)
epoch 70: w=Parameter containing:
tensor([[1.9378]], requires_grad=True), l=tensor(0.0405, grad_fn=<MseLossBackward0>)
epoch 80: w=Parameter containing:
tensor([[1.9404]], requires_grad=True), l=tensor(0.0372, grad_fn=<MseLossBackward0>)
epoch 90: w=Parameter containing:
tensor([[1.942

AttributeError: 'list' object has no attribute 'item'